### ISSUE TITLE
usage of code

### ISSUE THREAD

**Issue by pantchox** [dmarienko/trendspy#1]
Hi,

Care you to explain usage of each trend function in the code? i am interested in finding patterns in time series data, for example count of visits each day, or count of a tag each day on twitter.

thanks!

**Comment by dmarienko** [comment]
Hi, thanks for comment, that was planned as set of handy functions for detecting local trends in timeseries but not pattern finding tool like you described. I'm going to update it bit later by adding some other methods for trends highlighting and analysis.

For example if you have some timeseries data in x (like stock prices etc) you can call  
`rolling_series_slope` on x and it returns you rolling slope of local trend (based on given period) scaled to desired range (n_bins parameter). It can be used as some measure of trend's strenght on particular interval for example.
